# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2020
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "ğŸ¥"
subtitle = "Stay foolish stay hungry"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[article]
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "waline"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
js = "https://cdn.jsdelivr.net/npm/@waline/client/dist/Waline.min.js"
meta = ['nick','mail','link']                           # è¯„è®ºè€…ç›¸å…³å±æ€§
requiredMeta = ["name", "email", "url"]                        # è®¾ç½®å¿…å¡«é¡¹ï¼Œé»˜è®¤åŒ¿å
# login = "force"                                         # è¯„è®ºå¿…é¡»å…ˆç™»å½•ï¼Œç”¨äºé˜²æŠ¤æ¶æ„æ”»å‡»
# placeholder = "ä¸ºé˜²æ¶æ„çŒæ°´æ”»å‡»ï¼Œè¯„è®ºå‰éœ€æ³¨å†Œå¹¶ç™»å½•ï¼Œæœ›è§è°…~"     # è¯„è®ºæ¡†å ä½æç¤ºç¬¦
serverURL = "https://waline-line-git-main-zrsaber.vercel.app"                 # Walineçš„æœåŠ¡ç«¯åœ°å€ï¼ˆå¿…å¡«ï¼‰
#imageHosting =                                         # å›¾åºŠapiï¼Œå¦‚æœå…è®¸è¯„è®ºæ¡†ä¸Šä¼ å›¾ç‰‡
uploadImage = false                                     # è¯„è®ºä¸Šä¼ å›¾ç‰‡åŠŸèƒ½
avatar = "retro"                                        # Gravatarå¤´åƒ
avatarCDN = "https://sdn.geekzu.org/avatar/"            # Gravatarå¤´åƒCDNåœ°å€ï¼Œä¸å»ºè®®ä½¿ç”¨loliæº
pageSize = 20                                           # è¯„è®ºåˆ—è¡¨åˆ†é¡µï¼Œæ¯é¡µæ¡æ•°
lang = "zh-CN"                                          # å¤šè¯­è¨€æ”¯æŒ
visitor = true                                          # æ–‡ç« è®¿é—®é‡ç»Ÿè®¡
highlight = true                                        # ä»£ç é«˜äº®
# serverURL = ""
# lang = ""
# visitor = ""
# avatar = ""
# emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
# requiredMeta = ["name", "email", "url"]
placeholder = ""

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
